web:
  image: grzegorzwodo/seqr-ecommerce-base:PHP5_6
  ports:
    - "8080:80"
    - "3306:3306"
  volumes_from:
    - web-data
web-data:
  image: ikamman/ecommerce-prestashop-data
  environment:
    PLUGIN_NAME: 'seqr'
    PS_VERSION: '1.6.1.3'
  volumes:
    - ./seqr:/var/www/html/modules/seqr
